 name: Trendyol Scraper
  on:
    workflow_dispatch:
    schedule:
      - cron: '0 */6 * * *'
  jobs:
    scrape:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install packages
          run: |
            pip install requests beautifulsoup4 pandas
            pip install cloudscraper fake-useragent
        - name: List files
          run: ls -la
        - name: Run scraper
          run: |
            if [ -f "scrapers/trendyol_scraper.py" ]; then
              python3 scrapers/trendyol_scraper.py
            elif [ -f "api_endpoint_scraper.py" ]; then
              python3 api_endpoint_scraper.py
            elif [ -f "trendyol_scraper.py" ]; then
              python3 trendyol_scraper.py
            else
              echo "No scraper found"
            fi
        - name: Check results
          run: |
            python3 check_database.py || echo "No check script"
            ls -la *.db *.csv 2>/dev/null || echo "No output files yet"
        - uses: actions/upload-artifact@v3
          with:
            name: data
            path: |
              *.db
              *.csv
