 name: Trendyol Data Scraper

  on:
    schedule:
      - cron: '0 */4 * * *'  # Her 4 saatte bir
    workflow_dispatch:  # Manuel tetikleme

  jobs:
    scrape:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python3 github_advanced_scraper.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add market_spider.db scraped_products.csv
          git commit -m "Update: $(date)" || echo "No changes"
          git push
