 name: Trendyol Scraper
  on:
    workflow_dispatch:
  jobs:
    scrape:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: pip install requests beautifulsoup4 pandas cloudscraper fake-useragent
        - run: ls -la
        - run: python3 api_endpoint_scraper.py || echo "API scraper not found or failed"
        - run: python3 check_database.py || echo "Check script not found"
        - run: ls -la *.db *.csv || echo "No files generated"
        - uses: actions/upload-artifact@v3
          with:
            name: scraped-data
            path: |
              *.db
              *.csv
